services:
  bot-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/discord_bot}
      - ENVIRONMENT=development
    depends_on:
      - lavalink
    ports:
      - "8080:8080"  # For future web interface
    restart: unless-stopped
    networks:
      - lavalink
      - postgres

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"
    networks:
      - lavalink

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-discord_bot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  lavalink:
    driver: bridge
  postgres:
    driver: bridge