services:
  bot-prod:
    build:
      context: .
      target: production
    volumes:
      - ./data:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@postgres:5432/discord_bot}
      - ENVIRONMENT=production
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data: